// Generated by scripts/kampus/logos.py from static/logo-kampus. Codes whose logo file exists.
export const CAMPUS_LOGOS = new Set<string>(['ipb', 'itb', 'itera', 'itk', 'itpb', 'its', 'ivet', 'pkp-sorong', 'pnc', 'pnk', 'polinef', 'stai-siak', 'stai-tuntas', 'stt-migas', 'ub', 'ubt', 'ugm', 'ui', 'uir', 'unair', 'uncen', 'undip', 'unhas', 'unipa', 'unirow', 'unmul', 'unpatti', 'unri', 'uns', 'unsika', 'unsri', 'untirta', 'unud', 'unwir', 'uny', 'uper', 'upp', 'usb', 'usk', 'usu']);
export const logoSlug = (code: string) => code.toLowerCase().replace(/[^a-z0-9]+/g, '-');
/** Path of the campus logo, or empty when the campus has none yet. */
export const campusLogo = (code: string | null | undefined) => { const s = logoSlug(code || ''); return s && CAMPUS_LOGOS.has(s) ? `/logo-kampus/${s}.png` : ''; };
