import { test, expect, type Page } from '@playwright/test';
async function login(page: Page, role: 'admin' | 'campus') {
  await page.goto('/login');
  await page.getByRole('button', { name: role === 'admin' ? 'Masuk sebagai Admin PF' : 'Masuk sebagai Kampus' }).click();
  await expect(page).toHaveURL(new RegExp(`/${role}/dashboard$`));
}
async function logout(page: Page) {
  await page.locator('.sidebar').getByRole('button', { name: 'Keluar / ganti peran' }).click();
  await expect(page).toHaveURL(/\/login$/);
}

test('multi-topic questions, combined search, notification routing and persistent read state', async ({ page }) => {
  await login(page, 'campus');
  await page.goto('/campus/questions');
  await page.getByRole('button', { name: 'Proposal', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Bolehkah memperbarui proposal yang sudah diajukan?' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Apakah nilai aktual boleh melebihi target?' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Indikator & baseline', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Apakah nilai aktual boleh melebihi target?' })).toBeVisible();
  await page.getByLabel('Cari pertanyaan').fill('Baseline ditampilkan sebagai konteks awal');
  await expect(page.getByRole('heading', { name: 'Bagaimana cara menghitung capaian indikator DEB Putih?' })).toBeVisible();
  await page.getByRole('button', { name: 'Ajukan pertanyaan', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Umum', { exact: true }).uncheck();
  await dialog.getByLabel('Social Mapping', { exact: true }).check();
  await dialog.getByLabel('IKM', { exact: true }).check();
  await page.getByLabel('Judul pertanyaan').fill('QA kategori pemetaan');
  await page.getByLabel('Uraian pertanyaan').fill('Bagaimana menghubungkan dua instrumen?');
  await page.getByRole('button', { name: 'Bagikan pertanyaan' }).click();
  await expect(page).toHaveURL(/\/questions\/[^/]+$/);
  const questionId = page.url().split('/').at(-1)!;
  await expect(page.locator('.question-detail .category-tags')).toContainText('Social Mapping');
  await expect(page.locator('.question-detail .category-tags')).toContainText('IKM');
  await logout(page);
  await login(page, 'admin');
  await page.goto('/admin/notifications');
  const questionNotice = page.locator('.notification-list article').filter({ hasText: 'QA kategori pemetaan' });
  await expect(questionNotice).toContainText('Belum dibaca');
  await questionNotice.getByRole('link', { name: 'Lihat detail' }).click();
  await expect(page).toHaveURL(new RegExp(questionId));
  await page.getByLabel('Jawaban untuk semua kampus').fill('QA jawaban khusus pemetaan partisipatif.');
  await page.getByRole('button', { name: 'Simpan jawaban' }).click();
  await expect(page.getByText('QA jawaban khusus pemetaan partisipatif.', { exact: true })).toBeVisible();
  await page.goto('/admin/notifications');
  await expect(questionNotice).not.toContainText('Belum dibaca');
  await logout(page);
  await login(page, 'campus');
  await page.goto('/campus/notifications');
  const answerNotice = page.locator('.notification-list article').filter({ hasText: 'QA kategori pemetaan' });
  await expect(answerNotice).toContainText('Pertanyaan Anda telah dijawab');
  await answerNotice.getByRole('button', { name: 'Tandai dibaca', exact: true }).click();
  await page.reload();
  await expect(answerNotice).not.toContainText('Belum dibaca');
  await page.getByRole('button', { name: 'Tandai semua dibaca', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Tandai semua dibaca', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: /^Belum dibaca/ }).click();
  await expect(page.getByRole('heading', { name: 'Semua sudah dibaca' })).toBeVisible();
  await page.getByRole('button', { name: /^Semua / }).click();
  await page.screenshot({ path: 'test-results/notifications-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/notifications-mobile.png', fullPage: true });
  await page.goto('/campus/questions');
  await page.getByRole('button', { name: 'IKM', exact: true }).click();
  await page.getByLabel('Cari pertanyaan').fill('pemetaan partisipatif');
  await expect(page.getByRole('heading', { name: 'QA kategori pemetaan' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/forum-categories-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/forum-categories-desktop.png', fullPage: true });
});
