import { test, expect } from '@playwright/test';
import path from 'node:path';
import { LOCAL, readJson, adminClient, type LocalInstance } from '../../scripts/pocketbase/runtime';
test('real admin PIC editing, Mailpit activation in a fresh browser, campus login and logout',async({page,browser})=>{
  const fixture=await readJson<{adminEmail:string;password:string;campus:string;campusId:string;email:string}>(path.join(LOCAL,'p1-browser.json'));
  const instance=await readJson<LocalInstance>(path.join(LOCAL,'p1-test-instance.json'));expect(instance.kind).toBe('test');
  const root=await adminClient(instance);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/login');
  await expect(page.getByRole('link',{name:'Pratinjau login baru'})).toHaveCount(0);
  await expect(page.locator('.landscape svg')).toBeVisible();
  await page.getByLabel('Email PIC',{exact:true}).fill(fixture.adminEmail);
  await page.getByLabel('Password',{exact:true}).fill(fixture.password);
  await page.getByRole('button',{name:'Masuk',exact:true}).click();
  await expect(page).toHaveURL(/\/admin\/dashboard$/);
  await page.getByRole('link',{name:'Kampus mitra',exact:true}).filter({visible:true}).click();
  await page.getByRole('navigation',{name:'Pengelolaan kampus'}).getByRole('link',{name:'Akun kampus'}).click();
  await expect(page.locator('.account-row')).toHaveCount(10);
  await page.getByLabel('Cari kampus, PIC, atau email').fill(fixture.campus);
  const row=page.getByRole('article',{name:fixture.campus,exact:true});await expect(row).toBeVisible();
  await row.getByLabel('Nama PIC '+fixture.campus,{exact:true}).fill('PIC Browser');
  await row.getByLabel('Email '+fixture.campus,{exact:true}).fill(fixture.email);
  await page.getByRole('button',{name:/^Simpan perubahan/}).click();
  await expect(row.locator('.saved-pic')).toHaveText('PIC Browser');
  await page.reload();await page.getByLabel('Cari kampus, PIC, atau email').fill(fixture.campus);
  await expect(row.getByRole('link',{name:fixture.email,exact:true})).toBeVisible();
  await row.getByRole('button',{name:'Ubah PIC '+fixture.campus,exact:true}).click();
  await row.getByLabel('Nama PIC '+fixture.campus,{exact:true}).fill('Cancelled');
  await row.getByRole('button',{name:'Batal ubah PIC '+fixture.campus,exact:true}).click();
  await expect(row.locator('.saved-pic')).toHaveText('PIC Browser');
  await expect(page.getByRole('checkbox')).toHaveCount(0);
  await expect(page.getByRole('button',{name:/Kirim/})).toHaveCount(0);
  const campusContext=await browser.newContext();const campus=await campusContext.newPage();
  await campus.goto('/login');
  await campus.getByRole('button',{name:'Aktivasi akun',exact:true}).click();
  await expect(campus.getByRole('navigation',{name:'Tahapan aktivasi akun'})).toContainText('Langkah 1 dari 4');
  await campus.getByLabel('Email PIC',{exact:true}).fill(fixture.email);
  await campus.getByRole('button',{name:'Kirim tautan aktivasi',exact:true}).click();
  await expect(campus.getByRole('navigation',{name:'Tahapan aktivasi akun'})).toContainText('Langkah 2 dari 4');
  await page.getByRole('button',{name:'Muat ulang status',exact:true}).click();
  await expect(row).toContainText(/Dalam antrean|Menunggu aktivasi/);
  await root.crons.run('deb-email-queue');
  let messageId='';
  await expect.poll(async()=>{const data=await fetch('http://127.0.0.1:8025/api/v1/search?query='+encodeURIComponent('to:'+fixture.email)).then(r=>r.json());messageId=data.messages?.[0]?.ID||'';return !!messageId;}).toBe(true);
  const message=await fetch('http://127.0.0.1:8025/api/v1/message/'+messageId).then(r=>r.json());
  const link=String(message.Text).match(/http:\/\/127\.0\.0\.1:5177\/login\?token=[^\s]+/)![0];
  await campus.goto(link);await expect(campus.getByRole('heading',{name:'Buat password Anda.'})).toBeVisible();
  await expect(campus.getByRole('navigation',{name:'Tahapan aktivasi akun'})).toContainText('Langkah 3 dari 4');
  await expect(campus.locator('[aria-current=step]')).toContainText('Buat password');
  await expect(campus.locator('.account-summary')).toContainText(fixture.campus);
  await campus.getByLabel('Password baru',{exact:true}).fill('BrowserCampus123!');
  await campus.getByLabel('Konfirmasi password',{exact:true}).fill('BrowserCampus123!');
  await campus.getByRole('button',{name:'Simpan password',exact:true}).click();
  await expect(campus.getByRole('heading',{name:'Password berhasil disimpan.'})).toBeVisible();
  await expect(campus.getByRole('navigation',{name:'Tahapan aktivasi akun'})).toContainText('Langkah 4 dari 4');
  await campus.getByRole('button',{name:'Lanjut ke masuk'}).click();
  await campus.getByLabel('Password',{exact:true}).fill('BrowserCampus123!');
  await campus.getByRole('button',{name:'Masuk',exact:true}).click();
  await expect(campus).toHaveURL(/\/campus\/dashboard$/);
  await campus.reload();await expect(campus.locator('main.content')).toBeVisible();
  await page.getByRole('button',{name:'Muat ulang status',exact:true}).click();await expect(row).toContainText('Aktif');
  await campus.getByRole('button',{name:'Keluar / ganti akun'}).click();await expect(campus).toHaveURL(/\/login$/);
  expect((await campusContext.cookies()).some(c=>c.name==='deb_session')).toBe(false);
  await campusContext.close();expect(errors).toEqual([]);
});
test('login retains floral illustration, has no mockup entry and fits laptop/mobile viewport',async({page})=>{
  for(const size of [{width:1366,height:768},{width:1440,height:900},{width:390,height:844}]){
    await page.setViewportSize(size);await page.goto('/login?preview=p1');
    await expect(page.getByLabel('Email PIC',{exact:true})).toBeVisible();
    await expect(page.locator('.landscape svg')).toBeVisible();
    await expect(page.getByRole('link',{name:'Pratinjau login baru'})).toHaveCount(0);
    expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1 && document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await expect(page.getByRole('button',{name:'Masuk',exact:true})).toBeInViewport();
    await page.getByRole('button',{name:'Aktivasi akun',exact:true}).click();
    await expect(page.getByRole('navigation',{name:'Tahapan aktivasi akun'})).toContainText('Langkah 1 dari 4');
  }
  await page.getByLabel('Email PIC',{exact:true}).fill('not-registered-step-test@example.com');
  await page.getByRole('button',{name:'Kirim tautan aktivasi',exact:true}).click();
  await expect(page.getByRole('navigation',{name:'Tahapan aktivasi akun'})).toContainText('Langkah 2 dari 4');
});
