import 'fake-indexeddb/auto';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import Dexie from 'dexie';
import { createMockService } from '../src/lib/data/service';
import { createSeed, DEMO_CAMPUS } from '../src/lib/data/seed';
import { matchesQuestion, questionCategories } from '../src/lib/forum';
import type { DemoSession, Snapshot } from '../src/lib/types';
const admin: DemoSession = { role: 'admin', name: 'QA Admin' };
const campus: DemoSession = { role: 'campus', name: 'QA Kampus', campusId: DEMO_CAMPUS };
const service = () => createMockService(`deb-topics-${crypto.randomUUID()}`);

test('question categories validate and persist; search combines answers and OR category filters', async () => {
  const api = service();
  const id = await api.ask(campus, 'QA pembelajaran', 'Pertanyaan baru', ['social-mapping', 'ikm', 'ikm']);
  await api.answer(admin, id, 'Kata kunci jawaban: pemetaan partisipatif');
  const data = await api.load(campus);
  const question = data.questions.find(q => q.id === id)!;
  assert.deepEqual(question.categoryIds, ['social-mapping', 'ikm']);
  assert.ok(matchesQuestion(question, data.answers, 'PEMETAAN PARTISIPATIF', ['proposal', 'ikm']));
  assert.ok(!matchesQuestion(question, data.answers, '', ['proposal']));
  assert.ok(!matchesQuestion(question, data.answers, 'tidak ditemukan', ['ikm']));
  await assert.rejects(api.ask(campus, 'Gagal', 'Gagal', []), /kategori/);
  await assert.rejects(api.ask(campus, 'Gagal', 'Gagal', ['tidak-valid' as never]), /kategori/);
  assert.deepEqual(questionCategories({ title: 'Bolehkah memperbarui proposal yang sudah diajukan?' }), ['proposal']);
  assert.deepEqual(questionCategories({ title: 'Pertanyaan lama pengguna' }), ['umum']);
});

test('notifications follow recipient boundaries, read state, feedback, answers and updates', async () => {
  const api = service();
  await api.addFeedback(admin, `${DEMO_CAMPUS}-i1`, 'QA revisi khusus', true);
  await api.addFeedback(admin, 'campus-002-i1', 'QA revisi kampus lain', true);
  let inbox = (await api.load(campus)).notifications;
  const notice = inbox.find(n => n.body === 'QA revisi khusus')!;
  assert.equal(notice.recipient, 'campus'); assert.equal(notice.readAt, null);
  assert.ok(inbox.every(n => n.campusId === DEMO_CAMPUS && n.recipient === 'campus'));
  await assert.rejects(api.readNotifications(admin, [notice.id]), /bukan milik/);
  await api.readNotifications(campus, [notice.id]);
  const readAt = (await api.load(campus)).notifications.find(n => n.id === notice.id)!.readAt;
  assert.ok(readAt);
  await api.readNotifications(campus, [notice.id]);
  assert.equal((await api.load(campus)).notifications.find(n => n.id === notice.id)!.readAt, readAt);
  await api.updateIndicator(campus, `${DEMO_CAMPUS}-i1`, 18, 'QA capaian terbaru');
  const adminInbox = (await api.load(admin)).notifications;
  assert.ok(adminInbox.some(n => n.title === 'Data indikator diperbarui' && n.body.includes('QA capaian terbaru')));
  assert.ok(adminInbox.every(n => n.recipient === 'admin'));
  const id = await api.ask(campus, 'QA notifikasi pertanyaan', 'Isi', ['proposal']);
  await api.answer(admin, id, 'Jawaban');
  assert.ok((await api.load(campus)).notifications.some(n => n.href === `/campus/questions/${id}`));
  await api.readNotifications(campus);
  inbox = (await api.load(campus)).notifications;
  assert.ok(inbox.every(n => !!n.readAt));
  assert.ok((await api.load(admin)).notifications.some(n => !n.readAt));
});

test('legacy IndexedDB upgrades without resetting user proposals or indicator values', async () => {
  const name = `deb-upgrade-${crypto.randomUUID()}`;
  const db = new Dexie(name);
  db.version(1).stores({ state: 'id', files: 'id' });
  const { data, files } = createSeed();
  data.indicators[0].current = 987;
  delete (data as Partial<Snapshot>).notifications;
  delete data.notificationSeedVersion;
  await db.table('state').put({ id: 'main', data });
  await db.table('files').bulkPut(files);
  db.close();
  const api = createMockService(name);
  const loaded = await api.load(campus);
  assert.equal(loaded.indicators[0].current, 987);
  assert.equal(loaded.notifications.length, 5);
  assert.ok(loaded.notifications.every(n => n.simulated));
  assert.equal(loaded.proposals.length, 3);
  assert.ok((await api.proposalFile(campus, loaded.proposals[0].id)).size > 0);
  await api.addFeedback(admin, loaded.indicators[0].id, 'Setelah upgrade', true);
  assert.equal((await api.load(campus)).notifications.length, 6);
  await api.readNotifications(campus);
  const reloaded = await api.load(campus);
  assert.equal(reloaded.notifications.length, 6);
  assert.ok(reloaded.notifications.every(n => n.readAt));
});
