<script lang="ts">
  // Shared presentation for the explicit Campus/Admin routes.
  import { app } from '$lib/state.svelte';
  import { average, campusStats, date, percent } from '$lib/domain';
  import Stat from '$lib/components/Stat.svelte';
  import Progress from '$lib/components/Progress.svelte';
  import Icon from '$lib/components/Icon.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import CampusTable from '$lib/components/CampusTable.svelte';
  const isAdmin = $derived(app.session?.role === 'admin');
  const all = $derived((app.data?.campuses || []).map(c => ({ ...c, ...campusStats(app.data!, c.id) })));
  const own = $derived(campusStats(app.data!, app.session?.campusId || 'campus-001'));
  const overall = $derived(average(all.map(c => c.progress)));
  const submitted = $derived(all.filter(c => c.proposal).length);
  const needsAction = $derived(all.filter(c => c.revisions).length);
  const prefix = $derived(`/${app.session?.role}`);
  const activity = $derived([...(app.data?.activities || [])].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 4));
  const popular = $derived([...(app.data?.questions || [])].sort((a,b) => (app.data?.likes.filter(l => l.questionId === b.id).length || 0) - (app.data?.likes.filter(l => l.questionId === a.id).length || 0)).slice(0, 3));
</script>
<div class="page-heading"><div><span class="eyebrow">{isAdmin ? 'MONITORING KAMPUS MITRA' : 'RUANG KERJA KAMPUS'}</span><h1>{isAdmin ? 'Setiap langkah, berarti.' : 'Selamat datang, Universitas Contoh.'}</h1><p>{isAdmin ? 'Lihat perkembangan bersama dan temukan ruang untuk bertumbuh.' : 'Mari lanjutkan langkah untuk mewujudkan DEB Putih yang berdampak.'}</p></div><span class="period"><Icon name="clock" size={16}/>Periode 2026</span></div>
<section class="hero-banner"><div class="hero-copy"><span class="hero-label"><span></span>PROGRAM DEB PUTIH</span><h2>{isAdmin ? 'Kolaborasi terhubung.\nDampak terukur.' : 'Perubahan dimulai\ndari langkah Anda.'}</h2><p>{isAdmin ? 'Satu pandangan untuk perjalanan 40 kampus. Pantau capaian, berikan arahan, dan tumbuh bersama.' : 'Lengkapi data capaian, dokumentasikan perkembangan, dan bagikan pembelajaran bersama kampus lain.'}</p><a class="button mint" href={isAdmin ? '/admin/campuses' : '/campus/indicators'}>{isAdmin ? 'Jelajahi kampus mitra' : 'Perbarui indikator'}<Icon name="arrow" size={17}/></a></div><div class="hero-visual" aria-hidden="true"><div class="orbit one"></div><div class="orbit two"></div><div class="orbit three"></div><div class="hero-seed"><Icon name="leaf" size={70}/></div><span class="floating-card top"><Icon name="campus" size={18}/>40 kampus, satu visi</span><span class="floating-card bottom"><span class="mini-check"><Icon name="check" size={14}/></span>Tumbuh berkelanjutan</span></div></section>
<div class="stats-grid">{#if isAdmin}<Stat label="Kampus mitra" value={String(all.length)} note="Terhubung dalam program DEB" icon="campus"/><Stat label="Rata-rata progres" value={percent(overall)} note="Rata-rata capaian seluruh kampus" icon="target"/><Stat label="Proposal diajukan" value={`${submitted} / ${all.length}`} note="Kampus telah mengunggah proposal" icon="proposal"/><Stat label="Perlu tindak lanjut" value={String(needsAction)} note="Kampus dengan feedback revisi aktif" icon="alert" tone="amber"/>{:else}<Stat label="Progres DEB Putih" value={percent(own.progress)} note="Rata-rata capaian 30 indikator" icon="target"/><Stat label="Indikator tercapai" value={`${own.achieved} / ${own.total}`} note="Indikator sudah memenuhi target" icon="check"/><Stat label="Proposal terbaru" value={own.proposal ? `Versi ${own.proposal.version}` : 'Belum ada'} note={own.proposal ? 'Diajukan · ' + date(own.proposal.createdAt) : 'Unggah proposal pertama Anda'} icon="proposal"/><Stat label="Perlu tindak lanjut" value={String(own.revisions)} note="Indikator dengan feedback revisi aktif" icon="alert" tone="amber"/>{/if}</div>
<div class="dashboard-columns"><section class="panel"><div class="panel-heading"><div><h2>{isAdmin ? 'Perjalanan kampus mitra' : 'Capaian per bidang'}</h2><p>{isAdmin ? 'Perkembangan terbaru dari kampus yang terhubung.' : 'Setiap bidang berkontribusi pada progres bersama.'}</p></div><a class="text-link" href={isAdmin ? '/admin/campuses' : '/campus/indicators'}>Lihat semua<Icon name="arrow" size={16}/></a></div>{#if isAdmin}<CampusTable compact/>{:else}<div class="category-progress">{#each ['Tata kelola', 'Lingkungan', 'Pemberdayaan'] as category, index}{@const definitions = app.data!.definitions.filter(d => d.category === category).map(d => d.id)}{@const indicators = app.data!.indicators.filter(i => definitions.includes(i.definitionId))}{@const p = average(indicators.map(i => Math.min(i.current / i.target * 100, 100)))}<div class="category-row"><span class={`category-icon category-${index}`}><Icon name={['indicators', 'leaf', 'campus'][index]}/></span><div><div class="row-between"><strong>{category}</strong><strong>{percent(p)}</strong></div><Progress value={p} label={category}/><small>{indicators.filter(i => i.current >= i.target).length} dari {indicators.length} indikator tercapai</small></div></div>{/each}<div class="info-note"><Icon name="faq" size={17}/><span>Progres adalah rata-rata nilai aktual ÷ target, maksimal 100% untuk setiap indikator.</span></div></div>{/if}</section><section class="panel next-step"><span class="eyebrow">LANGKAH BERIKUTNYA</span><div class="next-icon"><Icon name="leaf" size={30}/></div><h2>{isAdmin ? 'Arahan kecil,\nkemajuan berarti.' : 'Lengkapi cerita\nperkembangan Anda.'}</h2><p>{isAdmin ? 'Tinjau indikator yang memerlukan perhatian dan bantu kampus mengambil langkah selanjutnya.' : 'Tanggapi masukan Admin dan pastikan capaian terbaru sudah tercatat.'}</p><a class="button secondary" href={isAdmin ? '/admin/verifikasi' : '/campus/indicators'}>{isAdmin ? 'Review pengajuan kampus' : 'Lihat feedback'}<Icon name="arrow" size={16}/></a></section></div>
<div class="dashboard-columns equal"><section class="panel"><div class="panel-heading"><div><h2>Aktivitas terbaru</h2><p>Jejak langkah dalam ruang kerja.</p></div><Icon name="clock" size={19}/></div><div class="activity-list">{#each activity as a}<div class="activity"><span class="activity-dot"></span><div><p>{a.text}</p><small>{isAdmin ? `${app.data!.campuses.find(c => c.id === a.campusId)?.name} · ` : ''}{date(a.createdAt)}</small></div></div>{/each}</div></section><section class="panel"><div class="panel-heading"><div><h2>Belajar dari pertanyaan bersama</h2><p>Percakapan yang membantu kampus bertumbuh.</p></div><a class="text-link" href={`${prefix}/questions`}>Buka forum<Icon name="arrow" size={16}/></a></div><div class="popular-list">{#each popular as q}<a href={`${prefix}/questions/${q.id}`}><span class="popular-like"><Icon name="like" size={15}/>{app.data!.likes.filter(l => l.questionId === q.id).length}</span><span><strong>{q.title}</strong><small>{app.data!.campuses.find(c => c.id === q.campusId)?.name}</small></span><Icon name="chevron" size={16}/></a>{/each}</div></section></div>
