<script lang="ts">
  // Shared presentation for the explicit Campus/Admin routes.
  import { app } from '$lib/state.svelte';
  import { dataService } from '$lib/data/service';
  import type { FaqEntry } from '$lib/types';
  import Icon from '$lib/components/Icon.svelte';
  import Modal from '$lib/components/Modal.svelte';
  import Empty from '$lib/components/Empty.svelte';
  let search = $state('');
  let editing = $state(false);
  let editId = $state<string | undefined>();
  let question = $state('');
  let answer = $state('');
  let removing = $state<FaqEntry | null>(null);
  const isAdmin = $derived(app.session?.role === 'admin');
  const all = $derived([...app.data!.faq].sort((a,b) => a.order - b.order));
  const entries = $derived(all.filter(f => `${f.question} ${f.answer}`.toLowerCase().includes(search.toLowerCase())));
  function edit(entry?: FaqEntry) { editId = entry?.id; question = entry?.question || ''; answer = entry?.answer || ''; editing = true; }
  async function save() { if (await app.mutate(() => dataService.saveFaq(app.session!, { id: editId, question, answer }), 'FAQ berhasil disimpan.')) editing = false; }
</script>
<div class="page-heading"><div><span class="eyebrow">PUSAT BANTUAN</span><h1>Jawaban untuk langkah Anda.</h1><p>Temukan panduan singkat seputar indikator, proposal, dan ruang kerja DEB.</p></div>{#if isAdmin}<button title="Hanya baca pada P2; penyimpanan menyusul P3" disabled={app.readOnly} class="button" onclick={() => edit()}><Icon name="plus" size={18}/>Tambah FAQ</button>{/if}</div>
<section class="faq-header"><div class="faq-header-icon"><Icon name="faq" size={36}/></div><h2>Apa yang ingin Anda ketahui?</h2><p>Pengetahuan bersama yang dikurasi oleh Admin PF.</p><div class="search-field"><Icon name="search" size={20}/><input aria-label="Cari FAQ" bind:value={search} placeholder="Cari jawaban, misalnya cara mengunggah proposal…"/></div></section>
<div class="faq-content"><div class="row-between faq-count"><h2>Pertanyaan yang sering ditanyakan</h2><span class="count">{entries.length} panduan</span></div>{#if entries.length}<div class="faq-list">{#each entries as f}<div class="faq-entry"><details><summary><span>{f.question}</span><Icon name="plus" size={20}/></summary><div class="faq-answer pre-wrap">{f.answer}</div></details>{#if isAdmin}<div class="faq-admin"><span>{f.questionId ? 'Dikurasi dari forum' : 'Panduan manual'}</span><div class="button-row"><button title="Hanya baca pada P2; penyimpanan menyusul P3" class="icon-button" aria-label={`Naikkan FAQ ${f.question}`} disabled={app.readOnly || (app.busy || all[0]?.id === f.id || !!search)} onclick={() => app.mutate(() => dataService.moveFaq(app.session!, f.id, -1), 'Urutan FAQ diperbarui.')}><Icon name="up" size={17}/></button><button title="Hanya baca pada P2; penyimpanan menyusul P3" class="icon-button" aria-label={`Turunkan FAQ ${f.question}`} disabled={app.readOnly || (app.busy || all.at(-1)?.id === f.id || !!search)} onclick={() => app.mutate(() => dataService.moveFaq(app.session!, f.id, 1), 'Urutan FAQ diperbarui.')}><Icon name="down" size={17}/></button><button title="Hanya baca pada P2; penyimpanan menyusul P3" disabled={app.readOnly} class="icon-button" aria-label={`Edit FAQ ${f.question}`} onclick={() => edit(f)}><Icon name="edit" size={17}/></button><button title="Hanya baca pada P2; penyimpanan menyusul P3" disabled={app.readOnly} class="icon-button danger-text" aria-label={`Hapus FAQ ${f.question}`} onclick={() => removing = f}><Icon name="trash" size={17}/></button></div></div>{/if}</div>{/each}</div>{:else}<section class="panel"><Empty title="Jawaban belum ditemukan" description="Coba kata kunci lain atau ajukan pertanyaan melalui forum bersama." icon="faq"/></section>{/if}<div class="faq-contact"><Icon name="questions" size={26}/><div><h3>Masih punya pertanyaan?</h3><p>Bagikan di forum agar seluruh kampus bisa belajar bersama.</p></div><a class="button secondary" href={`/${app.session?.role}/questions`}>Buka forum<Icon name="arrow" size={17}/></a></div></div>
{#if editing}<Modal title={editId ? 'Edit FAQ' : 'Tambah FAQ'} onclose={() => { if (!app.busy) editing = false; }}><form onsubmit={(e) => { e.preventDefault(); save(); }}><label>Pertanyaan FAQ<input readonly={app.readOnly} required maxlength="180" bind:value={question}/></label><label>Jawaban FAQ<textarea readonly={app.readOnly} required rows="6" maxlength="5000" bind:value={answer}></textarea></label><p class="muted">Isi FAQ dikelola terpisah dari jawaban di forum.</p><div class="dialog-actions"><button type="button" class="button secondary" onclick={() => editing = false}>Batal</button><button title="Hanya baca pada P2; penyimpanan menyusul P3" class="button" disabled={app.readOnly || (app.busy)}>{app.busy ? 'Menyimpan…' : 'Simpan FAQ'}</button></div></form></Modal>{/if}
{#if removing}<Modal title="Hapus FAQ ini?" onclose={() => { if (!app.busy) removing = null; }}><p>{removing.question}</p><p class="muted">FAQ akan dihapus dari pusat bantuan. Pertanyaan dan jawaban sumber di forum tetap tersedia.</p><div class="dialog-actions"><button class="button secondary" onclick={() => removing = null} disabled={app.busy}>Batal</button><button title="Hanya baca pada P2; penyimpanan menyusul P3" class="button danger" disabled={app.readOnly || (app.busy)} onclick={async () => { if (await app.mutate(() => dataService.deleteFaq(app.session!, removing!.id), 'FAQ dihapus.')) removing = null; }}>Hapus FAQ</button></div></Modal>{/if}
