"""
Normalises the fetched campus logos: trims empty margins, fits each into a 256 px square PNG with a transparent
background (white backgrounds of JPG sources are kept, since many seals need them), and writes the manifest
src/lib/campus-logos.ts that lists the codes with a logo. Also renders a contact sheet for a visual check.
Usage: python scripts/kampus/logos.py
"""
import io, os, re, sys
from PIL import Image, ImageChops, ImageDraw

sys.stdout.reconfigure(encoding='utf-8')
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'static', 'logo-kampus')
MANIFEST = os.path.join(ROOT, 'src', 'lib', 'campus-logos.ts')
SIZE = 256
MARGIN = 8


def trim(img: Image.Image) -> Image.Image:
    """Cuts transparent margins, or white margins when the image has no transparency."""
    if img.getchannel('A').getextrema()[0] < 255:
        box = img.getchannel('A').point(lambda a: 255 if a > 8 else 0).getbbox()
    else:
        bg = Image.new('RGB', img.size, (255, 255, 255))
        diff = ImageChops.difference(img.convert('RGB'), bg).convert('L').point(lambda v: 255 if v > 24 else 0)
        box = diff.getbbox()
    return img.crop(box) if box else img


def normalise(path: str) -> Image.Image:
    img = Image.open(path)
    img.load()
    img = img.convert('RGBA')
    img = trim(img)
    scale = (SIZE - 2 * MARGIN) / max(img.size)
    img = img.resize((max(1, round(img.width * scale)), max(1, round(img.height * scale))), Image.LANCZOS)
    canvas = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(img, ((SIZE - img.width) // 2, (SIZE - img.height) // 2), img)
    return canvas


codes = []
sheet = []
for name in sorted(os.listdir(SRC)):
    stem, ext = os.path.splitext(name)
    if ext.lower() not in ('.png', '.jpg', '.jpeg', '.gif', '.webp'):
        continue
    if ext.lower() == '.png' and stem in codes:
        continue
    path = os.path.join(SRC, name)
    out = normalise(path)
    target = os.path.join(SRC, stem + '.png')
    out.save(target, optimize=True)
    if ext.lower() != '.png':
        os.remove(path)
    codes.append(stem)
    sheet.append((stem, out))
    print(f'{stem}: {os.path.getsize(target) // 1024} KB')

# Contact sheet for the eye: six per row, code under each logo.
cols, cell = 6, 200
rows = (len(sheet) + cols - 1) // cols
board = Image.new('RGB', (cols * cell, rows * (cell + 24)), (240, 244, 250))
draw = ImageDraw.Draw(board)
for i, (stem, img) in enumerate(sheet):
    x, y = (i % cols) * cell, (i // cols) * (cell + 24)
    thumb = img.resize((cell - 40, cell - 40), Image.LANCZOS)
    board.paste(thumb, (x + 20, y + 10), thumb)
    draw.text((x + 20, y + cell - 20), stem, fill=(20, 40, 80))
board.save(os.path.join(SRC, '..', '..', 'logo-sheet.png'))

with io.open(MANIFEST, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by scripts/kampus/logos.py from static/logo-kampus. Codes whose logo file exists.\n')
    f.write('export const CAMPUS_LOGOS = new Set<string>([' + ', '.join(f"'{c}'" for c in codes) + ']);\n')
    f.write("export const logoSlug = (code: string) => code.toLowerCase().replace(/[^a-z0-9]+/g, '-');\n")
    f.write("/** Path of the campus logo, or empty when the campus has none yet. */\n")
    f.write("export const campusLogo = (code: string | null | undefined) => { const s = logoSlug(code || ''); return s && CAMPUS_LOGOS.has(s) ? `/logo-kampus/${s}.png` : ''; };\n")
print('manifest', len(codes), 'logos; sheet at logo-sheet.png in the repo root (delete after review)')
