<script lang="ts">
  import { page } from '$app/state';
  import { goto, replaceState } from '$app/navigation';
  import { dev } from '$app/environment';
  import { untrack } from 'svelte';
  import { app } from '$lib/state.svelte';
  import Icon from './Icon.svelte';
  import WelcomeGuide from './WelcomeGuide.svelte';
  let screen=$state<'login'|'activate'|'forgot'|'password'|'sent'|'success'|'invalid'>('login');
  let email=$state(''),password=$state(''),confirmation=$state(''),error=$state(''),busy=$state(false);
  let showPassword=$state(false),showConfirmation=$state(false),token=$state('');
  let flow=$state<'activate'|'forgot'>('activate');
  const activationSteps=['Email PIC','Periksa email','Buat password','Selesai'];
  const step=$derived(flow==='activate'?({activate:1,sent:2,password:3,success:4} as Partial<Record<typeof screen,number>>)[screen]||0:0);
  let target=$state({campus:'',name:'',email:'',purpose:'activate'});
  const longEnough=$derived(password.length>=8),hasNumber=$derived(/[0-9]/.test(password)),hasCapital=$derived(/[A-Z]/.test(password));
  const passwordsMatch=$derived(confirmation.length>0 && password===confirmation);
  const passwordRules=$derived([{label:'Minimal 8 karakter',met:longEnough},{label:'Mengandung angka',met:hasNumber},{label:'Mengandung huruf kapital',met:hasCapital}]);
  const title=$derived(({login:'Selamat datang kembali.',activate:'Aktivasi akun kampus.',forgot:'Lupa password?',password:target.purpose==='forgot'?'Buat password baru.':'Buat password Anda.',sent:'Periksa email Anda.',success:'Password berhasil disimpan.',invalid:'Tautan tidak dapat digunakan.'})[screen]);
  $effect(()=>{const value=page.url.searchParams.get('token');if(value)untrack(()=>{token=value;void inspect();});});
  async function api(operation:string,body:object){const r=await fetch('/api/auth/'+operation,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message||'Permintaan belum dapat diproses.');return data;}
  function go(next:typeof screen){if(next==='activate'||next==='forgot')flow=next;screen=next;error='';password='';confirmation='';showPassword=false;showConfirmation=false;}
  async function inspect(){busy=true;try{target=await api('inspect',{token});flow=target.purpose==='forgot'?'forgot':'activate';email=target.email;go('password');}catch{go('invalid');}finally{busy=false;}}
  async function submit(){busy=true;error='';try{
    if(screen==='login'){await api('login',{email,password});await app.login('');if(app.session)await goto('/'+app.session.role+'/dashboard');else throw new Error('Sesi belum dapat dimuat.');}
    else if(screen==='password'){if(!longEnough||!hasNumber||!hasCapital)throw new Error('Password minimal 8 karakter, mengandung angka dan huruf kapital.');if(password!==confirmation)throw new Error('Konfirmasi password belum sama.');await api('confirm',{token,password,passwordConfirm:confirmation});go('success');replaceState('/login',{});}
    else{await api('request',{email,purpose:screen==='forgot'?'forgot':'activate'});go('sent');}
  }catch(e){error=(e as Error).message;}finally{busy=false;}}
</script>
<svelte:head><title>Login - Digitalisasi DEB</title><meta name="robots" content="noindex,nofollow"/></svelte:head>
<main id="main-content" class="login-page auth-page" class:flow-page={step>0 || screen==='success'} class:success-page={screen==='success'} class:password-page={screen==='password'}>
  <section class="login-story"><a class="brand" href="/login"><span class="brand-mark"><Icon name="leaf" size={29}/></span><span>DEB<span class="brand-sub">RUANG TUMBUH BERSAMA</span></span></a><div class="login-copy"><span class="eyebrow light">DIGITALISASI DEB PUTIH</span><h1>Dari kolaborasi,<br/>tumbuh <em>perubahan.</em></h1><p>Satu ruang untuk merawat gagasan, memantau langkah, dan mewujudkan dampak bersama kampus mitra.</p><div class="login-metrics"><div><strong>40</strong><span>Kampus mitra</span></div><div><strong>PB</strong><span>Sumber data tunggal</span></div><div><strong>1</strong><span>Tujuan bersama</span></div></div></div><div class="landscape" aria-hidden="true"><span class="sun"></span><div class="hill back"></div><div class="hill front"></div><svg viewBox="0 0 460 220"><path d="M220 220V70m0 94c-75 0-95-60-95-90 60 0 95 25 95 90Zm0-43c75 0 100-65 100-110-72 0-100 42-100 110Z" fill="#c6e4a7"/><path d="m220 163-65-62m65 23 73-81" fill="none" stroke="#326747" stroke-width="3"/></svg></div><div class="login-footer"><img class="pf-white-logo" src="/logo-pf-white.png" alt="Pertamina Foundation" width="205" height="55"/><span>Untuk masa depan yang berkelanjutan.</span></div></section>
<section class="stage" aria-label="Akses akun">
<div class="stage-top"><span>PORTAL KAMPUS MITRA</span>{#if dev}<a href="/login?qa=1">Akun QA lokal</a>{/if}</div>
<div class="form-wrap">
{#if screen!=='login' && screen!=='success'}<button class="back" onclick={()=>go('login')}>Kembali ke masuk</button>{/if}
{#if step}<nav class="activation-progress" aria-label="Tahapan aktivasi akun"><p>Aktivasi akun <strong>Langkah {step} dari 4</strong></p><ol>{#each activationSteps as label,index}<li class:current={step===index+1} class:complete={step>index+1} aria-current={step===index+1?'step':undefined}><span class="step-number">{#if step>index+1}<Icon name="check" size={14}/>{:else}{index+1}{/if}</span><span>{label}</span></li>{/each}</ol></nav>{/if}
<div class="form-icon"><Icon name={screen==='success'?'check':screen==='invalid'?'alert':'leaf'} size={25}/></div>
<span class="section-label">AKSES AKUN DEB</span><h2>{title}</h2>
{#if ['login','activate','forgot','password'].includes(screen)}
<p class="intro">{screen==='login'?'Masuk menggunakan email PIC dan password akun kampus Anda.':screen==='password'?'Simpan password untuk melanjutkan akses akun kampus.':'Gunakan email PIC yang sudah didaftarkan admin DEB.'}</p>
{#if screen==='password'}<details class="intro-guide"><summary>Baru di DEB? Kenali ruang kerja Anda</summary><WelcomeGuide/></details><div class="account-summary"><Icon name="campus"/><div><strong>{target.campus}</strong><span>{target.name} - {target.email}</span></div></div>{/if}
<form onsubmit={e=>{e.preventDefault();void submit();}}>
{#if screen!=='password'}<label for="real-email">Email PIC</label><input id="real-email" type="email" autocomplete="email" required bind:value={email}/>{/if}
{#if screen==='login'||screen==='password'}
<div class="label-row"><label for="real-password">{screen==='password'?'Password baru':'Password'}</label>{#if screen==='login'}<button class="inline-link" type="button" onclick={()=>go('forgot')}>Lupa password?</button>{/if}</div>
<div class="password-input"><input id="real-password" type={showPassword?'text':'password'} autocomplete={screen==='login'?'current-password':'new-password'} required maxlength="128" aria-describedby={screen==='password'?'password-requirements':undefined} bind:value={password}/><button type="button" aria-label={showPassword?'Sembunyikan password':'Tampilkan password'} aria-pressed={showPassword} onclick={()=>showPassword=!showPassword}><Icon name={showPassword?'eye-off':'eye'} size={18}/></button></div>
{/if}
{#if screen==='password'}<ul id="password-requirements" class="password-rules" aria-label="Persyaratan password">{#each passwordRules as rule}<li class:met={rule.met}><span class="rule-icon" aria-hidden="true">{#if rule.met}<Icon name="check" size={12}/>{:else}<span></span>{/if}</span><span>{rule.label}</span><span class="sr-only">{rule.met?'Terpenuhi':'Belum terpenuhi'}</span></li>{/each}</ul><label for="real-confirm">Konfirmasi password</label><div class="password-input"><input id="real-confirm" type={showConfirmation?'text':'password'} autocomplete="new-password" required maxlength="128" aria-describedby="password-match" bind:value={confirmation}/><button type="button" aria-label={showConfirmation?'Sembunyikan konfirmasi password':'Tampilkan konfirmasi password'} aria-pressed={showConfirmation} onclick={()=>showConfirmation=!showConfirmation}><Icon name={showConfirmation?'eye-off':'eye'} size={18}/></button></div><p id="password-match" class="password-match" class:met={passwordsMatch} class:mismatch={!!confirmation&&!passwordsMatch} aria-live="polite"><span aria-hidden="true">{#if passwordsMatch}<Icon name="check" size={13}/>{/if}</span>{passwordsMatch?'Konfirmasi password cocok.':confirmation?'Konfirmasi password belum cocok.':'Ketik ulang password yang sama.'}</p>{/if}
{#if error}<p class="error" role="alert">{error}</p>{/if}
<button class="primary" disabled={busy || (screen==='password' && (!longEnough || !hasNumber || !hasCapital || !passwordsMatch))}>{busy?'Memproses...':screen==='login'?'Masuk':screen==='password'?'Simpan password':screen==='forgot'?'Kirim tautan pemulihan':'Kirim tautan aktivasi'}<Icon name="arrow" size={18}/></button>
</form>
{#if screen==='login'}<div class="first-time"><span>Pertama kali menggunakan DEB?</span><button onclick={()=>go('activate')}>Aktivasi akun</button></div>{/if}
{:else if screen==='sent'}<p class="intro">Jika email terdaftar dan memenuhi syarat, tautan akan dikirim. Periksa inbox dan folder spam.</p><button class="primary" onclick={()=>go('login')}>Kembali ke masuk</button>
{:else if screen==='success'}<p class="intro">Kenali DEB, lalu masuk dengan email dan password Anda.</p><WelcomeGuide/><button class="primary" onclick={()=>go('login')}>Lanjut ke masuk</button>
{:else}<p class="intro">Tautan mungkin kedaluwarsa, sudah digunakan, atau telah diganti. Minta tautan baru sesuai kebutuhan akun Anda.</p><button class="primary" onclick={()=>go('activate')}>Minta tautan aktivasi</button><button class="inline-link" onclick={()=>go('forgot')}>Pemulihan password</button>{/if}
</div><footer class="stage-footer"><img class="pf-color-logo" src="/logo-pf.png" alt="Pertamina Foundation" width="140" height="37"/><span>Digitalisasi DEB</span></footer>
</section></main>
<style>
.auth-page{min-height:100svh}.login-story{min-height:100svh;padding-top:32px;padding-bottom:28px}.login-copy{margin-top:clamp(32px,7vh,75px)}.login-footer{padding-top:24px}.login-metrics{margin-top:28px}.stage{padding:32px 48px;display:flex;flex-direction:column}.stage-top{display:flex;justify-content:space-between;gap:15px;font-size:10px;color:#6d839f}.stage-top a{color:#1768c0;text-decoration:underline}.form-wrap{width:100%;max-width:420px;margin:auto;padding:50px 0}.form-icon{display:inline-grid;place-items:center;width:48px;height:48px;background:#edf5ff;border:1px solid #d5e6fb;border-radius:13px;color:#2373cd;margin-bottom:26px}.section-label{display:block;font-size:9px;letter-spacing:2px;color:#6d89ab;margin-bottom:12px}h2{font-size:30px;line-height:1.3;letter-spacing:-1px}.intro{font-size:12px;line-height:1.9;color:#7185a0;margin:17px 0 25px}form{display:flex;flex-direction:column;gap:10px}label{font-size:12px;color:#335580;margin-top:7px}input{min-width:0;width:100%;min-height:48px;border:1px solid #cdddf1;border-radius:8px;padding:12px 14px;color:#24466f;background:white;font-size:13px}.label-row{display:flex;justify-content:space-between;align-items:center}.password-input{position:relative}.password-input input{padding-right:48px}.password-input button{position:absolute;right:5px;top:5px;display:grid;place-items:center;width:38px;height:38px;border:0;background:transparent;color:#4b719c}.primary{display:flex;align-items:center;justify-content:center;gap:13px;width:100%;min-height:48px;padding:13px 18px;border-radius:8px;border:0;background:#1668d4;color:white;font-size:12px;font-weight:650;margin-top:17px}.primary:disabled{opacity:.5;cursor:wait}.inline-link,.back{color:#276bb7;font-size:11px;background:transparent;border:0}.back{display:block;margin-bottom:25px}.first-time{display:grid;gap:9px;text-align:center;margin-top:25px;font-size:11px;color:#7085a0}.first-time button{color:#1668d4;background:none;border:0;font-weight:650}.account-summary{display:flex;gap:12px;align-items:center;padding:17px;background:#edf5ff;border:1px solid #d8e7f8;border-radius:9px;color:#2d79ca;margin:22px 0}.account-summary div{min-width:0;display:grid;gap:6px}.account-summary strong{font-size:12px}.account-summary span{font-size:11px;color:#6b82a0;overflow-wrap:anywhere}.error{font-size:11px;color:#a33b31;background:#fff0ee;padding:12px;border-radius:7px;line-height:1.7}.stage-footer{font-size:10px;color:#8092aa;text-align:center}button{cursor:pointer}
@media(max-width:700px){.login-story{min-height:330px}.auth-page{display:block}.stage{padding:24px}.form-wrap{padding:30px 0}h2{font-size:26px}}

/* Keep the login composition within the viewport without clipping form controls. */
.auth-page{min-height:100dvh}.login-story{min-height:0;height:100dvh;padding-block:clamp(20px,4vh,36px)}.stage{min-height:100dvh;padding-block:clamp(16px,3vh,28px)}.form-wrap{padding-block:clamp(16px,3vh,30px)}
@media(min-width:701px) and (max-height:800px){.form-icon{width:38px;height:38px;margin-bottom:14px}.form-wrap{padding-block:12px}.intro{margin:12px 0 16px}.first-time{margin-top:16px}.primary{margin-top:10px}.login-copy h1{font-size:clamp(34px,5.5vh,44px)}.login-copy{margin-top:5vh}.login-copy>p{margin-top:16px}.login-metrics{margin-top:20px}}
@media(max-width:700px){.auth-page{display:flex;flex-direction:column}.login-story{height:clamp(145px,24dvh,200px);min-height:0;padding:18px 24px;flex-shrink:0}.login-story .brand{font-size:23px}.login-copy{margin-top:14px}.login-copy .eyebrow,.login-copy>p{display:none}.login-copy h1{font-size:clamp(21px,3.2vh,27px);margin-top:0;max-width:270px;line-height:1.15}.landscape{height:170px}.landscape>svg{width:220px;right:-55px}.stage{flex:1;min-height:0;padding:16px 24px}.form-wrap{padding:16px 0}.form-icon{display:none}.section-label{margin-bottom:8px}h2{font-size:24px}.intro{margin:10px 0 16px;font-size:11px}.first-time{margin-top:16px}.stage-footer{padding-top:16px}.primary{margin-top:12px}.stage-top{font-size:9px}.account-summary{margin:12px 0;padding:12px}}

.activation-progress{margin:0 0 24px}.activation-progress>p{display:flex;justify-content:space-between;gap:12px;margin:0 0 15px;font-size:10px;color:#6580a1}.activation-progress strong{color:#1768c0;font-weight:650}.activation-progress ol{list-style:none;padding:0;margin:0;display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.activation-progress li{position:relative;display:flex;flex-direction:column;align-items:center;gap:8px;color:#7c8fa7;font-size:9px;text-align:center;line-height:1.4}.activation-progress li:not(:last-child):after{content:'';position:absolute;left:calc(50% + 19px);right:calc(-50% + 11px);top:15px;height:2px;background:#d9e4f2}.step-number{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#edf2f8;border:1px solid #d4e0ee;color:#7b91ad;font-size:11px;font-weight:650}.activation-progress li.current{color:#155fb9;font-weight:700}.current .step-number{background:#176bd6;border-color:#176bd6;color:white;box-shadow:0 0 0 4px #e7f1ff}.activation-progress li.complete{color:#23764f}.complete .step-number{background:#e7f6ee;border-color:#b6ddc9;color:#23764f}.activation-progress li.complete:after{background:#a1d3bc}.flow-page .form-icon{display:none}.flow-page .back{margin-bottom:18px}.flow-page .intro{margin:12px 0 17px}
@media(max-width:700px){.flow-page .login-story{height:100px;min-height:100px;padding-block:18px}.flow-page .login-copy{display:none}.flow-page .landscape{height:120px}.flow-page .form-wrap{padding-block:12px}.activation-progress{margin-bottom:18px}.flow-page .account-summary{margin:12px 0}.flow-page .stage-footer{padding-top:10px}}
/* Let the illustration stretch with the form on short screens instead of ending early. */
@media(min-width:701px){.auth-page .login-story{height:auto;min-height:100dvh;align-self:stretch}}
.password-rules{list-style:none;padding:0;margin:2px 0 6px;display:grid;gap:6px;font-size:11px;color:#7185a0}
.password-rules li{display:flex;align-items:center;gap:8px;line-height:1.5}.rule-icon{width:17px;height:17px;display:grid;place-items:center;border:1px solid #cbd9e9;border-radius:50%;flex-shrink:0}.rule-icon>span{width:4px;height:4px;border-radius:50%;background:#91a3ba}.password-rules .met,.password-match.met{color:#187347}.met .rule-icon{background:#e7f6ec;border-color:#a2d4b6}.password-match{display:flex;align-items:center;gap:5px;min-height:18px;font-size:11px;color:#7185a0;margin:0}.password-match.mismatch{color:#b42318}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.password-page .stage{padding-block:16px}.password-page .form-wrap{padding-block:10px}.password-page .back{margin-bottom:12px}.password-page .activation-progress{margin-bottom:16px}.password-page .activation-progress>p{margin-bottom:10px}.password-page .section-label{margin-bottom:7px}.password-page h2{font-size:28px}.password-page .intro{margin:8px 0 12px}.password-page .account-summary{margin:12px 0 16px;padding:12px 14px}.password-page form{gap:8px}.password-page label{margin:0}.password-page .label-row{margin:0}.password-page .primary{margin-top:6px}.password-page .primary:disabled{cursor:not-allowed}
@media(max-width:700px){.password-page h2{font-size:24px}.password-page .stage-top{display:none}.password-page .stage{padding-block:12px}.password-page .form-wrap{padding-block:0}.password-page .stage-footer{padding-top:10px}}
.pf-white-logo{width:180px;height:auto;margin-bottom:4px}.stage-footer .pf-color-logo{display:none}.stage-footer{display:grid;justify-items:center;gap:6px}.intro-guide{margin:10px 0;font-size:11px;color:#2368b5}.intro-guide summary{cursor:pointer;line-height:1.6}.intro-guide[open] summary{margin-bottom:12px}
@media(max-width:700px){.stage-footer .pf-color-logo{display:block;width:116px;height:auto}.stage-footer>span{font-size:9px}}
@media(min-width:701px) and (max-height:800px){.password-page .stage{padding-block:10px}.password-page .activation-progress{margin-bottom:10px}.password-page .account-summary{margin:8px 0 12px}.password-page .form-wrap{padding-block:6px}}
.success-page .stage{padding-block:14px}.success-page .form-wrap{padding-block:10px}.success-page h2{font-size:26px}.success-page .section-label{margin-bottom:7px}.success-page .back{margin-bottom:12px}.success-page .activation-progress{margin-bottom:14px}.success-page .intro{margin:10px 0 14px}.success-page .primary{margin-top:12px}
@media(max-width:700px){.success-page .stage-top{display:none}.success-page .stage{padding-block:8px}}
</style>
