<script lang="ts">
  import { goto } from '$app/navigation';
  import { app } from '$lib/state.svelte';
  import Icon from '$lib/components/Icon.svelte';
  import type { Role } from '$lib/types';
  $effect(() => { if (app.ready && app.session) goto(`/${app.session.role}/dashboard`, { replaceState: true }); });
  async function login(role: Role) { if (await app.login(role)) goto(`/${role}/dashboard`); }
</script>
<svelte:head><title>Masuk · Digitalisasi DEB</title></svelte:head>
<main id="main-content" class="login-page">
  <section class="login-story"><a class="brand" href="/login"><span class="brand-mark"><Icon name="leaf" size={29}/></span><span>DEB<span class="brand-sub">RUANG TUMBUH BERSAMA</span></span></a><div class="login-copy"><span class="eyebrow light">DIGITALISASI DEB PUTIH</span><h1>Dari kolaborasi,<br/>tumbuh <em>perubahan.</em></h1><p>Satu ruang untuk merawat gagasan, memantau langkah, dan mewujudkan dampak bersama kampus mitra.</p><div class="login-metrics"><div><strong>40</strong><span>Kampus mitra</span></div><div><strong>30</strong><span>Indikator capaian</span></div><div><strong>1</strong><span>Tujuan bersama</span></div></div></div><div class="landscape" aria-hidden="true"><span class="sun"></span><div class="hill back"></div><div class="hill front"></div><svg viewBox="0 0 460 220"><path d="M220 220V70m0 94c-75 0-95-60-95-90 60 0 95 25 95 90Zm0-43c75 0 100-65 100-110-72 0-100 42-100 110Z" fill="#c6e4a7"/><path d="m220 163-65-62m65 23 73-81" fill="none" stroke="#326747" stroke-width="3"/></svg></div><div class="login-footer">PERTAMINA FOUNDATION <span>Untuk masa depan yang berkelanjutan.</span></div></section>
  <section class="login-panel"><div class="login-form"><span class="demo-label"><span></span>Prototype · Data simulasi</span><h2>Selamat datang.</h2><p class="login-intro">Pilih ruang kerja Anda untuk mulai menjelajahi Digitalisasi DEB.</p><button class="role-card" disabled={app.loading || !app.ready} onclick={() => login('campus')}><span class="role-icon"><Icon name="campus" size={28}/></span><span><strong>Masuk sebagai Kampus</strong><small>Pantau capaian dan kelola program Anda.</small></span><Icon name="arrow"/></button><button class="role-card" disabled={app.loading || !app.ready} onclick={() => login('admin')}><span class="role-icon admin"><Icon name="globe" size={28}/></span><span><strong>Masuk sebagai Admin PF</strong><small>Dampingi dan pantau seluruh kampus mitra.</small></span><Icon name="arrow"/></button>{#if app.loading}<p role="status">Menyiapkan data simulasi…</p>{/if}<div class="login-hint"><Icon name="faq" size={18}/><p>Anda akan masuk tanpa email atau kata sandi. Seluruh data adalah simulasi dan tersimpan di browser ini.</p></div><p class="login-bottom">Kolaborasi yang terhubung. Dampak yang terukur.</p></div></section>
</main>
